# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0009_add_incicent_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[(b'email', b'Email')], max_length=60)),
                ('value', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60)),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('business_lines', models.ManyToManyField(related_name='_notificationtemplate_business_lines_+', to='incidents.BusinessLine')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together=set([('user', 'key')]),
        ),
        migrations.AlterIndexTogether(
            name='notificationpreference',
            index_together=set([('user', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='methodconfiguration',
            unique_together=set([('user', 'key')]),
        ),
        migrations.AlterIndexTogether(
            name='methodconfiguration',
            index_together=set([('user', 'key')]),
        ),
    ]
