# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_async', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='business_lines',
            field=models.ManyToManyField(blank=True, related_name='_notificationtemplate_business_lines_+', to='incidents.BusinessLine'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='short_description',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
