# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir_async', '0002_auto_20160930_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='enabled',
            new_name='disabled',
        ),
    ]
