# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-02 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_async', '0003_auto_20160930_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='key',
            new_name='event',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='method',
            field=models.CharField(choices=[(b'email', b'Email')], default='email', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together=set([('user', 'event', 'method')]),
        ),
        migrations.AlterIndexTogether(
            name='notificationpreference',
            index_together=set([('user', 'event', 'method')]),
        ),
    ]
