# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_add_incicent_permissions'),
        ('fir_async', '0004_auto_20161002_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='business_lines',
            field=models.ManyToManyField(blank=True, related_name='_notificationpreference_business_lines_+', to='incidents.BusinessLine'),
        ),
        migrations.AlterField(
            model_name='methodconfiguration',
            name='key',
            field=models.CharField(choices=[(b'xmpp', b'XMPP'), (b'email', b'Email')], max_length=60),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='method',
            field=models.CharField(choices=[(b'xmpp', b'XMPP'), (b'email', b'Email')], max_length=60),
        ),
    ]
