# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-10 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir_async', '0005_auto_20161009_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='disabled',
        ),
    ]
