# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_async', '0006_remove_notificationpreference_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodconfiguration',
            name='key',
            field=models.CharField(choices=[(b'email', b'Email'), (b'xmpp', b'XMPP')], max_length=60),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='method',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(choices=[('action:created', 'Action created'), ('action:updated', 'Action updated')], max_length=60),
        ),
    ]
