# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir_async', '0007_auto_20161010_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodconfiguration',
            options={'verbose_name': 'method configuration', 'verbose_name_plural': 'method configurations'},
        ),
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'verbose_name': 'notification preference', 'verbose_name_plural': 'notification preferences'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'verbose_name': 'notification template', 'verbose_name_plural': 'notification templates'},
        ),
        migrations.AlterField(
            model_name='methodconfiguration',
            name='key',
            field=models.CharField(choices=[(b'email', b'Email'), (b'xmpp', b'XMPP')], max_length=60, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='methodconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_preferences', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='methodconfiguration',
            name='value',
            field=models.TextField(verbose_name='configuration'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='business_lines',
            field=models.ManyToManyField(blank=True, related_name='_notificationpreference_business_lines_+', to='incidents.BusinessLine', verbose_name='business lines'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event',
            field=models.CharField(max_length=60, verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='method',
            field=models.CharField(max_length=60, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='business_lines',
            field=models.ManyToManyField(blank=True, related_name='_notificationtemplate_business_lines_+', to='incidents.BusinessLine', verbose_name='business line'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(choices=[('action:created', 'Action created'), ('action:updated', 'Action updated')], max_length=60, verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='subject'),
        ),
    ]
